### ISSUE TITLE
Hi i have a problem with node.js and nativefier

### ISSUE THREAD

**Issue by markazie** [LockheedInnovation/Project-NodeJS#1]
when type this command in node.js:
$ nativefier "http://example.com.com"
or
$ nativefier maps.google.com
i get this error :
SyntaxError: Unexpected indentifier
at Object.exports.createScript (vm.js:24:10)
at REPLServer.defaultEval (repl.js:225:25)
at bound (domain.js:287:14)
at REPLServer.runBound as eval
at REPLServer. (repl.js:417:12)
at emitOne (events.js:82:20)
at REPLServer.emit (events.js:169:7)
at REPLServer.Interface._onLine (readline.js:210:10)
at REPLServer.Interface._line (readline.js:549:8)
at REPLServer.Interface._ttyWrite (readline.js:826:14)

Please help to solve this issue.

BR

**Comment by towsonTigers** [comment]
This is not part of this project.
